=== raphael3653/conf_godinho/.dev/lp_json_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Linha de Produção",
    "description": "Schema da Linha de Produção do SAP",
    "type": "object",
    "properties": {
      "nome": {
        "type": "string"
      },
      "descricao": {
        "type": "string"
      },
      "versao": {
        "type": "string"
      },
      "nome_abrev": {
        "type": "string"
      },
      "tipo_produto_id": {
        "type": "integer"
      },
      "fases": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "tipo_fase_id": {"type": "integer"},
            "ordem": {"type": "integer"},
            "subfases": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "nome": {"type": "string"},
                  "ordem": {"type": "integer"}
                },
                "required": ["nome", "ordem"]
              }
            },
            "pre_requisito_subfase": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                    "subfase_anterior": {"type": "string"},
                    "subfase_posterior": {"type": "string"},
                    "tipo_pre_requisito_id": {"type": "integer"}
                },
                "required": ["subfase_anterior", "subfase_posterior", "tipo_pre_requisito_id"]
                }
            }
          },
          "required": ["tipo_fase_id", "ordem", "subfases"]
        }
      },
      "propriedades_camadas": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "schema": {"type": "string"},
            "camada": {"type": "string"},
            "subfase": {"type": "string"},
            "camada_apontamento": {"type": "boolean"},
            "camada_incomum": {"type": "boolean"},
            "atributo_filtro_subfase": {"type": "string"},
            "atributo_situacao_correcao": {"type": "string"},
            "atributo_justificativa_apontamento": {"type": "string"}
          },
          "required": ["schema", "camada", "subfase", "camada_apontamento", "camada_incomum"]
        }
      }
    },
    "required": ["nome", "descricao", "versao", "nome_abrev", "tipo_produto_id", "fases", "propriedades_camadas"]
  }

=== raphael3653/conf_godinho/edgv_topo/1_4/linha_producao/lp_cdgv_edgv_30topo14.json
{
    "nome": "Conjunto de dados geoespaciais vetoriais para EDGV 3.0 Topo 1.4",
    "descricao": "Linha de produção padrão para vetores da EDGV",
    "versao": "1.0.0",
    "nome_abrev": "cdgv_edgv_3topo14",
    "tipo_produto_id": 7,
    "fases": [
        {
            "tipo_fase_id": 16,
            "ordem": 1,
            "subfases": [
                {
                    "nome": "Coleta de Insumos Externos",
                    "ordem": 1
                },
                {
                    "nome": "Preparo das Imagens",
                    "ordem": 2
                },
                {
                    "nome": "Preparo da Altimetria",
                    "ordem": 3
                }
            ],
            "pre_requisito_subfase": []
        },
        {
            "tipo_fase_id": 1,
            "ordem": 2,
            "subfases": [
                {
                    "nome": "Extração de Ferrovia",
                    "ordem": 1
                },
                {
                    "nome": "Extração da Hidrografia e Altimetria",
                    "ordem": 2
                },
                {
                    "nome": "Extração de Topônimos",
                    "ordem": 3
                },
                {
                    "nome": "Extração de Vias de Deslocamento",
                    "ordem": 4
                },
                {
                    "nome": "Extração de Elemento Hidrográfico",
                    "ordem": 5
                },
                {
                    "nome": "Extração de Área sem Dados",
                    "ordem": 6
                },
                {
                    "nome": "Extração de Limites",
                    "ordem": 7
                },
                {
                    "nome": "Extração de Interseção de Hidrografia e Transporte",
                    "ordem": 8
                },
                {
                    "nome": "Extração de Área Edificada",
                    "ordem": 9
                },
                {
                    "nome": "Extração de Edificação",
                    "ordem": 10
                },
                {
                    "nome": "Extração de Vegetação",
                    "ordem": 11
                },
                {
                    "nome": "Extração de Planimetria",
                    "ordem": 12
                },
                {
                    "nome": "Verificação Final",
                    "ordem": 13
                }
            ],
            "pre_requisito_subfase": [
                {
                    "subfase_anterior": "Extração de Ferrovia",
                    "subfase_posterior": "Extração de Vias de Deslocamento",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Ferrovia",
                    "subfase_posterior": "Extração de Ferrovia",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração da Hidrografia e Altimetria",
                    "subfase_posterior": "Extração de Elemento Hidrográfico",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração da Hidrografia e Altimetria",
                    "subfase_posterior": "Extração da Hidrografia e Altimetria",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Topônimos",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Topônimos",
                    "subfase_posterior": "Extração de Topônimos",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Vias de Deslocamento",
                    "subfase_posterior": "Extração de Área sem Dados",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Vias de Deslocamento",
                    "subfase_posterior": "Extração de Interseção de Hidrografia e Transporte",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Vias de Deslocamento",
                    "subfase_posterior": "Extração de Vias de Deslocamento",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Elemento Hidrográfico",
                    "subfase_posterior": "Extração de Área sem Dados",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Elemento Hidrográfico",
                    "subfase_posterior": "Extração de Interseção de Hidrografia e Transporte",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Elemento Hidrográfico",
                    "subfase_posterior": "Extração de Elemento Hidrográfico",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Área sem Dados",
                    "subfase_posterior": "Extração de Limites",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Área sem Dados",
                    "subfase_posterior": "Extração de Área Edificada",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Vias de Deslocamento",
                    "subfase_posterior": "Extração de Área Edificada",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Elemento Hidrográfico",
                    "subfase_posterior": "Extração de Área Edificada",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Área sem Dados",
                    "subfase_posterior": "Extração de Área sem Dados",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Limites",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Limites",
                    "subfase_posterior": "Extração de Limites",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Interseção de Hidrografia e Transporte",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Interseção de Hidrografia e Transporte",
                    "subfase_posterior": "Extração de Interseção de Hidrografia e Transporte",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Área Edificada",
                    "subfase_posterior": "Extração de Edificação",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Área Edificada",
                    "subfase_posterior": "Extração de Vegetação",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Área Edificada",
                    "subfase_posterior": "Extração de Área Edificada",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Edificação",
                    "subfase_posterior": "Extração de Planimetria",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Edificação",
                    "subfase_posterior": "Extração de Edificação",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Vegetação",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Vegetação",
                    "subfase_posterior": "Extração de Vegetação",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Extração de Planimetria",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 1
                },
                {
                    "subfase_anterior": "Extração de Planimetria",
                    "subfase_posterior": "Extração de Planimetria",
                    "tipo_pre_requisito_id": 2
                },
                {
                    "subfase_anterior": "Verificação Final",
                    "subfase_posterior": "Verificação Final",
                    "tipo_pre_requisito_id": 2
                }
            ]
        },
        {
            "tipo_fase_id": 3,
            "ordem": 3,
            "subfases": [
                {
                    "nome": "Validação Nível Produto",
                    "ordem": 1
                },
                {
                    "nome": "Validação da Ligação",
                    "ordem": 2
                }
            ],
